// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: home_page.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomePageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Business *Business          `protobuf:"bytes,1,opt,name=business,proto3" json:"business,omitempty"`
	Users    []*FrontEndUser    `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Bookings []*BookingResponse `protobuf:"bytes,3,rep,name=bookings,proto3" json:"bookings,omitempty"`
}

func (x *HomePageResponse) Reset() {
	*x = HomePageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_home_page_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomePageResponse) ProtoMessage() {}

func (x *HomePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_page_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomePageResponse.ProtoReflect.Descriptor instead.
func (*HomePageResponse) Descriptor() ([]byte, []int) {
	return file_home_page_proto_rawDescGZIP(), []int{0}
}

func (x *HomePageResponse) GetBusiness() *Business {
	if x != nil {
		return x.Business
	}
	return nil
}

func (x *HomePageResponse) GetUsers() []*FrontEndUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *HomePageResponse) GetBookings() []*BookingResponse {
	if x != nil {
		return x.Bookings
	}
	return nil
}

var File_home_page_proto protoreflect.FileDescriptor

var file_home_page_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x0e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01,
	0x0a, 0x10, 0x68, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x52, 0x08, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31,
	0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x62, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x42,
	0x0d, 0x48, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x6d,
	0x73, 0x66, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x5f, 0x67, 0x65, 0x6e,
	0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x56, 0x58, 0x58, 0xaa, 0x02, 0x02, 0x56, 0x31, 0xca, 0x02,
	0x02, 0x56, 0x31, 0xe2, 0x02, 0x0e, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x02, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_home_page_proto_rawDescOnce sync.Once
	file_home_page_proto_rawDescData = file_home_page_proto_rawDesc
)

func file_home_page_proto_rawDescGZIP() []byte {
	file_home_page_proto_rawDescOnce.Do(func() {
		file_home_page_proto_rawDescData = protoimpl.X.CompressGZIP(file_home_page_proto_rawDescData)
	})
	return file_home_page_proto_rawDescData
}

var file_home_page_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_home_page_proto_goTypes = []interface{}{
	(*HomePageResponse)(nil), // 0: v1.homePageResponse
	(*Business)(nil),         // 1: v1.business
	(*FrontEndUser)(nil),     // 2: v1.frontEndUser
	(*BookingResponse)(nil),  // 3: v1.bookingResponse
}
var file_home_page_proto_depIdxs = []int32{
	1, // 0: v1.homePageResponse.business:type_name -> v1.business
	2, // 1: v1.homePageResponse.users:type_name -> v1.frontEndUser
	3, // 2: v1.homePageResponse.bookings:type_name -> v1.bookingResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_home_page_proto_init() }
func file_home_page_proto_init() {
	if File_home_page_proto != nil {
		return
	}
	file_business_proto_init()
	file_user_proto_init()
	file_book_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_home_page_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomePageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_home_page_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_home_page_proto_goTypes,
		DependencyIndexes: file_home_page_proto_depIdxs,
		MessageInfos:      file_home_page_proto_msgTypes,
	}.Build()
	File_home_page_proto = out.File
	file_home_page_proto_rawDesc = nil
	file_home_page_proto_goTypes = nil
	file_home_page_proto_depIdxs = nil
}
