// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: location_services.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LocationServices with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LocationServices) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LocationServices with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LocationServicesMultiError, or nil if none found.
func (m *LocationServices) ValidateAll() error {
	return m.validate(true)
}

func (m *LocationServices) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PickupLocationWithDock

	// no validation rules for LiftGatePickup

	// no validation rules for PickupAppointment

	// no validation rules for InsidePickup

	// no validation rules for PickupNotification

	// no validation rules for ShipperDeliveryNotification

	// no validation rules for DeliveryLocationWithDock

	// no validation rules for LiftGateDelivery

	// no validation rules for DeliveryAppointment

	// no validation rules for InsideDelivery

	// no validation rules for ReceiverPickupNotification

	// no validation rules for DeliveryNotification

	if len(errors) > 0 {
		return LocationServicesMultiError(errors)
	}

	return nil
}

// LocationServicesMultiError is an error wrapping multiple validation errors
// returned by LocationServices.ValidateAll() if the designated constraints
// aren't met.
type LocationServicesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LocationServicesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LocationServicesMultiError) AllErrors() []error { return m }

// LocationServicesValidationError is the validation error returned by
// LocationServices.Validate if the designated constraints aren't met.
type LocationServicesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LocationServicesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LocationServicesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LocationServicesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LocationServicesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LocationServicesValidationError) ErrorName() string { return "LocationServicesValidationError" }

// Error satisfies the builtin error interface
func (e LocationServicesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLocationServices.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LocationServicesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LocationServicesValidationError{}
