// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: menu.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateMenuData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateMenuData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMenuData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateMenuDataMultiError,
// or nil if none found.
func (m *CreateMenuData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMenuData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CousineType

	if len(errors) > 0 {
		return CreateMenuDataMultiError(errors)
	}

	return nil
}

// CreateMenuDataMultiError is an error wrapping multiple validation errors
// returned by CreateMenuData.ValidateAll() if the designated constraints
// aren't met.
type CreateMenuDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMenuDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMenuDataMultiError) AllErrors() []error { return m }

// CreateMenuDataValidationError is the validation error returned by
// CreateMenuData.Validate if the designated constraints aren't met.
type CreateMenuDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMenuDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMenuDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMenuDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMenuDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMenuDataValidationError) ErrorName() string { return "CreateMenuDataValidationError" }

// Error satisfies the builtin error interface
func (e CreateMenuDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMenuData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMenuDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMenuDataValidationError{}

// Validate checks the field values on MenuResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MenuResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MenuResponseMultiError, or
// nil if none found.
func (m *MenuResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Success

	if len(errors) > 0 {
		return MenuResponseMultiError(errors)
	}

	return nil
}

// MenuResponseMultiError is an error wrapping multiple validation errors
// returned by MenuResponse.ValidateAll() if the designated constraints aren't met.
type MenuResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuResponseMultiError) AllErrors() []error { return m }

// MenuResponseValidationError is the validation error returned by
// MenuResponse.Validate if the designated constraints aren't met.
type MenuResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuResponseValidationError) ErrorName() string { return "MenuResponseValidationError" }

// Error satisfies the builtin error interface
func (e MenuResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuResponseValidationError{}
