// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shipment_details.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ShipmentDetails with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ShipmentDetails) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShipmentDetails with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ShipmentDetailsMultiError, or nil if none found.
func (m *ShipmentDetails) ValidateAll() error {
	return m.validate(true)
}

func (m *ShipmentDetails) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for QuoteId

	// no validation rules for RequesterId

	// no validation rules for Mode

	// no validation rules for LiablePartyId

	// no validation rules for PickupDate

	// no validation rules for DisplayDate

	// no validation rules for DeliveryDate

	// no validation rules for TotalItems

	// no validation rules for TotalWeight

	// no validation rules for ValidUntil

	// no validation rules for EditMode

	// no validation rules for BusinessId

	// no validation rules for Type

	if len(errors) > 0 {
		return ShipmentDetailsMultiError(errors)
	}

	return nil
}

// ShipmentDetailsMultiError is an error wrapping multiple validation errors
// returned by ShipmentDetails.ValidateAll() if the designated constraints
// aren't met.
type ShipmentDetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShipmentDetailsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShipmentDetailsMultiError) AllErrors() []error { return m }

// ShipmentDetailsValidationError is the validation error returned by
// ShipmentDetails.Validate if the designated constraints aren't met.
type ShipmentDetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShipmentDetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShipmentDetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShipmentDetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShipmentDetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShipmentDetailsValidationError) ErrorName() string { return "ShipmentDetailsValidationError" }

// Error satisfies the builtin error interface
func (e ShipmentDetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShipmentDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShipmentDetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShipmentDetailsValidationError{}
